spring:
  application:
    name: leads
  r2dbc:
    url: "r2dbc:postgresql://crmleads.ch4g8uw2igs6.ap-south-1.rds.amazonaws.com:5432/crmleads?sslmode=require"
    username: "ajay"
    password: "yJiJktREM>V].*U_xZ2.shv4TVlG"
  datasource:
    url: "jdbc:postgresql://crmleads.ch4g8uw2igs6.ap-south-1.rds.amazonaws.com:5432/crmleads?sslmode=require"
    username: "ajay"
    password: "yJiJktREM>V].*U_xZ2.shv4TVlG"
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: "jdbc:postgresql://crmleads.ch4g8uw2igs6.ap-south-1.rds.amazonaws.com:5432/crmleads?sslmode=require"
    user: "ajay"
    password: "yJiJktREM>V].*U_xZ2.shv4TVlG"
logging:
  level:
    org.springframework.security: DEBUG
    org.flywaydb.core.internal.scanner: DEBUG
    com.crm.users: DEBUG
    org.flywaydb: INFO
    org.flywaydb.core.internal.command: DEBUG
app:
  jwtSecret: "aGVsbG93b3JsZHRoaXNpc2FzZWN1cmVzZWNyZXQxMjM0NTY="
  jwtExpiration: 86400000
aws:
  secretname: "rds!db-efa93a37-8e6e-4d85-b060-7ee1cba6b723"
